name: mbank_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-374.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Navigator
  auto_route: ^4.0.1

  # Service
  equatable: ^2.0.3
  dartz: ^0.10.1
  url_launcher: ^6.1.4
  intl: ^0.17.0

  # Service Locator
  get_it: ^7.2.0

  # Presentation
  pull_to_refresh_flutter3: ^2.0.1 # pagination
  shimmer: ^2.0.0
  figma_squircle: ^0.5.3
  transparent_image: ^2.0.1

  # Generator
  flutter_gen: ^4.1.6
  font_awesome_flutter: ^10.3.0

  # State management
  flutter_bloc: ^8.0.1

  # API
  dio: ^4.0.6
  connectivity_plus: ^2.0.2
  pretty_dio_logger: ^1.1.1
  internet_connection_checker: ^0.0.1+3

  # Hook
  flutter_hooks: ^0.18.5+1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generator
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.2.0
  auto_route_generator: ^4.0.0

  flutter_lints: ^2.0.0

flutter_gen:
  line_length: 80 # Optional (default: 80)

  assets:
    enabled: true
    package_parameter_enabled: false

    fonts:
      enabled: true

flutter:
  uses-material-design: true

  fonts:
    - family: Currency
      fonts:
        - asset: assets/fonts/Currency.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
